### ISSUE TITLE
No PPS-out while HOLDOVER

### ISSUE THREAD

**Issue by vvfedorenko** [Orolia2s/art-card-board#2]
We found huge difference in PTP testing while ART-Card is in holdover state. Although oscillatord shows small offset when GNSS signal is back, the diff in service quality was really bad, and the root cause is absence of PPS out from ART-Card to NIC.
Logs of oscillatord and ts2phc are attached to this issue
[oscillatord.log.txt](https://github.com/Orolia2s/art-card-board/files/8361926/oscillatord.log.txt)
[ts2phc.log.txt](https://github.com/Orolia2s/art-card-board/files/8361927/ts2phc.log.txt)

**Comment by CharlesParent** [comment]
Hi @vvfedorenko,

Could you tell me which revision you tested, wether it's rev 3 or 4 ?

Could you also tell me which SMA port you used to get the PPS our ?

**Comment by leoleovich** [comment]
@CharlesParent Rev3, PPS out pin 4.

**Comment by CharlesParent** [comment]
The static SMA mapping for Rev3 is the following:
IO 1 (J9): PPS IN
IO 2 (J3): 10MHz Output
IO 3 (J4): PPS OUT0 (PPS mRO)
IO 4 (J7): PPS OUT1 (PPS uBlox)

You should be using IO 3 to connect to the NIC.

**Comment by vvfedorenko** [comment]
Ok, with new version we have PPS out on IO 4 even during Holdover, cool.
Another problem is about oscillatord, will create another issue in its project
